export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_ALL_PRODUCT_ASYNC = "GET_ALL_PRODUCT_ASYNC"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_ASYNC = "ADD_PRODUCT_ASYNC"

export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const DELETE_PRODUCT_ASYNC = 'DELETE_PRODUCT_ASYNC'

export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const EDIT_PRODUCT_ASYNC="EDIT_PRODUCT_ASYNC"

export const BUTTON_LOADER_SATRT = "BUTTON_LOADER_SATRT"
export const BUTTON_LOADER_END = "BUTTON_LOADER_END"